const types = {
  POKEDEX_INIT_REQUEST: '@pokedex/INIT_REQUEST',
  POKEDEX_INIT_SUCCESS: '@pokedex/INIT_SUCCESS',
  POKEDEX_INIT_FAILURE: '@pokedex/INIT_FAILURE',
  POKEDEX_FILTER_REQUEST: '@pokedex/FILTER_REQUEST',
  POKEDEX_FILTER_SUCCESS: '@pokedex/FILTER_SUCCESS',
  POKEDEX_FILTER_FAILURE: '@pokedex/FILTER_FAILURE',
  POKEMON_SAVE_REQUEST: '@pokemon/SAVE_REQUEST',
  POKEMON_SAVE_SUCCESS: '@pokemon/SAVE_SUCCESS',
  POKEMON_SAVE_FAILURE: '@pokemon/SAVE_FAILURE',
  FAVORITE_SAVE_REQUEST: '@favorite/SAVE_REQUEST',
  FAVORITE_SAVE_SUCCESS: '@favorite/SAVE_SUCCESS',
  FAVORITE_SAVE_FAILURE: '@favorite/SAVE_FAILURE'
}

export default types
